-- CreateTable
CREATE TABLE `records` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `date` DATE NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `details` VARCHAR(255) NULL,
    `inAmount` INTEGER UNSIGNED NULL,
    `outAmount` INTEGER UNSIGNED NULL,
    `memo` TEXT NULL,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
